# Create unit file and start
- name: "Create systemd service script for Tomcat"
  template:
    src: tomcat.service.j2
    dest: "/etc/systemd/system/tomcat.service"
  notify: restart tomcat

- name: "Start and enable Tomcat service"
  systemd:
    name: tomcat
    state: started
    enabled: true
    daemon_reload: true
  notify: tomcat_facts