---
- name: add group "tomcat"
  group:
    name: "{{ group_ }}"
    gid: "{{ gid_ }}"

- name: add user "tomcat"
  user:
    name: "{{ usr_ }}"
    group: "{{ group_ }}"
    home: "{{ home_dir }}"
    createhome: no
  become: True
  become_method: sudo

- name: Install tar
  yum:
    name: tar
    state: present

- name: Download Tomcat
  get_url:
    url: http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-{{ tomcat_ver }}.tar.gz
    dest: /opt/apache-tomcat-7.0.61.tar.gz

- name: Extract archive
  unarchive:
    src: /opt/apache-tomcat-7.0.61.tar.gz
    dest: /opt/
    creates: /opt/apache-tomcat-7.0.61

- name: Symlink install directory
  file:
    src: /opt/apache-tomcat-7.0.61
    path: /usr/share/tomcat
    state: link

- name: Change ownership of Tomcat installation
  file:
    path: /usr/share/tomcat/
    owner: "{{ usr_ }}"
    group: "{{ group_ }}"
    state: directory
    recurse: yes

- name: Configure Tomcat server
  template:
    src: server.xml
    dest: /usr/share/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat users
  template:
    src: tomcat-users.xml
    dest: /usr/share/tomcat/conf/
  notify: restart tomcat

- name: Install Tomcat init script
  copy:
    src: tomcat-initscript.sh
    dest: /etc/init.d/tomcat
    mode: 0755

- name: Start Tomcat
  shell: /opt/apache-tomcat-7.0.61/bin/startup.sh

- name: wait for tomcat to start
  wait_for:
    port: "{{ http_port }}"