# Java configuration
- name: Set JAVA_HOME
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^JAVA_HOME"
    line: "JAVA_HOME={{ full_java_name }}"

- name: Set/Configure JAVA_HOME in environment variables
  shell: "echo 'export JAVA_HOME={{ full_java_name }}\n export PATH=$JAVA_HOME/bin:$PATH' > {{ java_env_file }}"

- name: Exports/Run java env file for make JAVA_HOME available globally
  shell: "source {{ java_env_file }}"

- name: Configurastion of alternatives
  shell: "alternatives --install /usr/bin/{{ item }} {{ item }} {{ full_java_name }}/bin/{{ item }} 2"
  loop:
    - java
    - javac
    - jar

