# Gatheringfacts
- name: "Create facts directory"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Get Java version"
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_version
  notify: java_facts