---
# tasks file for java
- name: "Check if java is already installed or not"
  shell: "{{ full_java_name }}/bin/java -version 2>&1 | grep version | awk '{print $3}' | sed 's/\"//g'"
  register: java_version

- name: "Installed java version"
  debug: "msg={{ java_version.stdout }}"

- block:
  - name: "Java installation"
    include_tasks: install.yml
    when: '"install" in tasks'

  - name: "Java configuration"
    include_tasks: configure.yml
    when: '"configure" in tasks'

  - name: "Gathering facts"
    include_tasks: facts.yml
    when: '"facts" in tasks'

  - name: "Gathering results"
    include_tasks: results.yml
    when: '"results" in tasks'

  tags:
    - java
  when: java_version.stdout == ""


#  - name: Copy java archive
#    copy:
#      src: "jdk-{{ java_ver }}_linux-x64_bin.tar.gz"
#      dest: "{{ java_dest }}"

#  - name: Java installation
#    unarchive:
#      src: "{{ java_dest }}jdk-{{ java_ver }}_linux-x64_bin.tar.gz"
#      dest: "{{ java_dest }}"
#      remote_src: yes

#  - name: Set JAVA_HOME
#    lineinfile:
#      dest: "/etc/environment"
#      state: present
#      regexp: "^JAVA_HOME"
#      line: "JAVA_HOME={{ full_java_name }}"

#  - name: Set/Configure JAVA_HOME in environment variables
#    shell: "echo 'export JAVA_HOME={{ full_java_name }}\n export PATH=$JAVA_HOME/bin:$PATH' > {{ java_env_file }}"

#  - name: Exports/Run java env file for make JAVA_HOME available globally
#    shell: "source {{ java_env_file }}"

#  - name: Configurastion of alternatives
#    shell: "alternatives --install /usr/bin/{{ item }} {{ item }} {{ full_java_name }}/bin/{{ item }} 2"
#    loop:
#      - java
#      - javac
#      - jar

#  - name: Create facts directory
#    file:
#      path: "/etc/ansible/facts.d"
#      state: "directory"

#  - name: Get Java version
#    shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
#    register: java_result
#    notify: java_facts

#  - name: Result of installation
#    debug:
#      msg: "Failed - Java is not installed"
#    when: java_result is failed

#  - name: Result of installation
#    debug:
#      msg: "Success - Java is installed"
#    when: java_result is success
