---
# handlers file for httpd
- name: restart apache
  service:
    name: httpd
    state: restarted

- name: httpd facts
  copy:
    content: >
      {
        "HTTPD version": "{{ httpd_version }}"
      }
    dest: /etc/ansible/facts.d/httpd_facts.fact