---
# tasks file for httpd
- name: "Check if java is already installed or not"
  shell: httpd -v 2>&1 | grep version | awk '{print $3}' | sed 's/\//-/'
  register: httpd_version

- name: "Check HTTPD installation"
  debug: "msg={{ httpd_version.stdout }}"

- block:
  - name: "Install httpd"
    include_tasks: yum.yml
    when: '"yum" in tasks'

  - name: "Copy .conf files"
    include_tasks: copy.yml
    when: '"copy" in tasks'

  - name: "Create facts directory"
    include_tasks: facts.yml
    when: '"facts" in tasks'

  - name: "Start httpd and facts it"
    include_tasks: start.yml
    when: '"start" in tasks'

  tags:
    - httpd
  when: httpd_version.stdout == ""

- rescue:
  - debug:
      msg: 'Error is occured, Install latest version of httpd'
  - name: "Install httpd latest version"
    yum:
      name: httpd
      state: present
    register: httpd_version

- always:
    - debug: "var=httpd_version.stdout"


#- name: install one specific version of Apache
#  yum:
#    name: httpd-{{ httpd_ver }}.el7.centos
#    state: present
#  register: status

#- name: Status of proxy.conf on remote server
#  stat:
#    path: "{{ path_dest }}{{ service_ }}"
#  register: copy_status

#- name: Dont copy proxy.conf to remote server if it exists
#  copy:
#    src: "{{ service_ }}"
#    dest: "{{ path_dest }}{{ service_ }}"
#  when: copy_status.stat.exists == False

#- name: Create facts directory
#  file:
#    path: "/etc/ansible/facts.d"
#    state: "directory"

#- name: Enable Apache on system reboot
#  service:
#    name: httpd
#    enabled: yes
#  notify:
#    - restart apache
#    - httpd facts

