---
# tasks file for docker-install
- name: "Install Docker"
  yum:
    name: "{{ docker_package }}"
    state: latest
  become: yes

- name: "Start Docker service"
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
  notify: docker facts
