# Create user account
- name: "Add User"
  user:
    name: "{{ username }}"
    uid: "{{ uid }}"
    groups: "{{ groups_name }}"
    home: "{{ home_dir | default(omit) }}"
    state: present
    createhome: yes