# tasks file for user
- name: "Add User"
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
  when: '"add_user" in tasks_'
  become: yes

#- name: "Copy authorized keys"
#  include_tasks: add_key.yml
#  when: '"add_key" in tasks'
