Vagrant.configure("2") do |config|
  config.vm.define "ansible_exit" do |ansible_exit|
  ansible_exit.vm.box = "sbeliakou/centos"
  ansible_exit.vm.hostname = "ansibleexit"
  ansible_exit.vm.network :private_network, ip: "192.168.56.101"
  ansible_exit.vm.provider "virtualbox" do |vb|
    vb.name = "ansibleexit"
    vb.memory = "2048"
    end
  end
end
